mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('new/', views.CreateItem.as_view(), name='create_item'),
    path('<int:pk>/edit/', views.edit, name='edit_item'),
    path('<int:pk>/delete/', views.delete, name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.profile_page, name='profile')
]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_descr = models.CharField(max_length=250)
    price = models.IntegerField()
    item_img = models.CharField(max_length=1000, default="https://alllocal.ca/wp-content/uploads/2020/11/food-placeholder.png")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)
    phone_num = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_descr', 'price', 'item_img']

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }

    return render(request, 'index.html', context)


class IndexClassView(ListView):
    """Class based view instead of old view."""
    model = Item
    template_name = 'index.html'
    context_object_name = 'item_list'


def detail(request, pk):
    item = Item.objects.get(pk=pk)
    context = {
        'item': item,
    }

    return render(request, 'detail.html', context)


class FoodDetail(DetailView):
    model = Item
    template_name = 'detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'item_form.html', {'form': form})


class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_descr', 'price', 'item_img']
    template_name = 'item_form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)



def edit(request, pk):
    item = Item.objects.get(pk=pk)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'item_form.html', {'form': form, 'item': item})


def delete(request, pk):
    item = Item.objects.get(pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'item_delete.html', {'item': item})

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome, {username}, your account is created!')
            return redirect('users:login')

    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

@login_required
def profile_page(request):
    return render(request, 'profile.html')

mysite/food/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
 <head>
  <meta charset="UTF-8" />
  <title>Index</title>
 <link rel="stylesheet" href="{% static 'food/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
 </head>
 <body>
 <nav class="navbar navbar-dark bg-dark">
   <a href="/food/" class="navbar-brand">Food app</a>
  <div class="navbar">
      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'food:create_item' %}">Add Item</a>
      <a class="nav-item" href="#">Delete</a>
      <a class="nav-item" href="#">View item</a>
      <a class="nav-item" href="{% url 'users:profile' %}">Profile</a>

      <form method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit">logout</button>
</form>
        {% else %}
            <a class="nav-item" href="{% url 'users:login' %}">Login</a>
      {% endif %}
  </div>
 </nav>
 {% if messages %}
     {% for message in messages %}
    <div class="alert alert-{{ message.tag }}">{{ message }}</div>
     {% endfor %}
 {% endif %}

{% block body %}
 {% endblock %}

 </body>
</html>

mysite/food/templates/detail.html
{% extends 'base.html' %}
 {% block body %}
 <div class="container">
  <div class="row">
   <div class="col-md-6">
      <img src="{{ item.item_img }}" height="400px">
   </div>
      <div class="col-md-6">
       <h1> {{item.item_name }}</h1>
       <h5> Description: {{item.item_descr }}</h5>
       <h6> Author: {{item.user_name }}</h6>
       <h6> Price: ${{item.price }}</h6>
       <a href="{% url 'food:delete_item' item.id %}">Delete</a>

   </div>
  </div>
 </div>


 {% endblock %}
 </body>
</html>

mysite/food/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body %}

 {% for item in item_list %}
<div class="row">
  <div class="col-md-3 offset-md-2">
         <img src="{{ item.item_img }}" height="160px">
  </div>
  <div class="col-md-4">

    <a href="{% url 'food:detail' item.id %}"><h3>{{ item.item_name }}</h3></a>
    <h5>{{ item.item_descr }}</h5>
    <h6>${{ item.price }}</h6>
  </div>
  <div class="col-md-2">
   <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
  </div>
</div>
 {% endfor %}
 {% endblock %}

 </body>
</html>

mysite/food/templates/item_delete.html
{% extends 'base.html' %}
 {% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <p>Do you really want to delete {{ item.item_name }}?</p>
    <button type="submit">Delete</button>
</form>
 {% endblock %}

mysite/food/templates/item_form.html
{% extends 'base.html' %}
 {% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card-header text-white bg-info">
                <div class="card-title">Login
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button class="btn-info" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mysite/users/templates/login.html
{% extends 'base.html' %}
 {% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card-header text-white bg-info">
                <div class="card-title">Login
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button class="btn-info" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mysite/users/templates/profile.html
{% extends 'base.html' %}
 {% block body %}
<h1>{{ user.username }}</h1>
<img width="100px" src="{{ user.profile.image.url }}">
<p>{{ user.profile.phone_num}}</p>
<p>{{ user.profile.image.url }}</p>
{% endblock %}

mysite/users/templates/register.html
{% extends 'base.html' %}
 {% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card-header text-white bg-info">
                <div class="card-title">Login
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button class="btn-info" type="submit">Signup</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}